[zos_mainframe]
localhost ansible_connection=local

[zos_mainframe:vars]
ansible_python_interpreter=auto_silent
zos_uss_root=/tmp/mock_zos/uss
zos_pds_loadlib=MY.LOADLIB
env_type=SIMULATED_DEVELOPMENT
